version: '3'
services:
  mongo:
    image: library/mongo:4.2-bionic
    container_name: 'zoomSpeedDating-mongo'
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-config:/data/configdb
    ports:
      - 27017-27019:27017-27019
